from datetime import date
from typing import Annotated
from uuid import UUID

from fastapi import APIRouter, Depends, Query

from app.core.config import Settings, get_settings
from app.core.dependencies import DbSession
from app.integrations.ai.forecasting_service import ForecastingIntegrationService
from app.modules.auth.dependencies import require_permissions
from app.modules.forecasting.repository import ForecastRepository
from app.modules.forecasting.schemas import (
    ForecastCreateRequest,
    ForecastGenerateRequest,
    ForecastListResponse,
    ForecastResponse,
)
from app.modules.forecasting.service import ForecastService
from app.modules.inventory.repository import InventoryRepository
from app.modules.orders.repository import OrderRepository
from app.modules.products.repository import ProductRepository
from app.modules.shared.permissions import Permission
from app.modules.users.models import User
from app.schemas.pagination import PageMeta

router = APIRouter(prefix="/forecasts", tags=["forecasting"])


async def get_forecast_service(
    session: DbSession,
    settings: Annotated[Settings, Depends(get_settings)],
) -> ForecastService:
    return ForecastService(
        forecast_repository=ForecastRepository(session),
        product_repository=ProductRepository(session),
        order_repository=OrderRepository(session),
        inventory_repository=InventoryRepository(session),
        forecasting_provider=ForecastingIntegrationService(
            model_name=settings.forecasting_model_name,
            model_version=settings.forecasting_model_version,
        ),
    )


ForecastServiceDep = Annotated[ForecastService, Depends(get_forecast_service)]


@router.get(
    "",
    response_model=ForecastListResponse,
    summary="List forecasts",
    description=(
        "Returns paginated forecast output records with product, status, "
        "period, and search filters."
    ),
)
async def list_forecasts(
    service: ForecastServiceDep,
    _: Annotated[User, Depends(require_permissions(Permission.VIEW_FORECASTS))],
    product_id: UUID | None = Query(default=None),
    status: str | None = Query(default=None),
    period_start: date | None = Query(default=None),
    period_end: date | None = Query(default=None),
    search: str | None = Query(default=None, min_length=1, max_length=120),
    offset: int = Query(default=0, ge=0),
    limit: int = Query(default=50, ge=1, le=100),
) -> ForecastListResponse:
    items = await service.list_forecasts(
        product_id=product_id,
        status=status,
        period_start=period_start,
        period_end=period_end,
        search=search,
        offset=offset,
        limit=limit,
    )
    return ForecastListResponse(
        items=list(items),
        meta=PageMeta(offset=offset, limit=limit, count=len(items)),
    )


@router.post(
    "",
    response_model=ForecastResponse,
    status_code=201,
    summary="Store forecast output",
    description=(
        "Stores a forecast result generated by a future forecasting runtime "
        "or an approved batch job."
    ),
)
async def create_forecast(
    payload: ForecastCreateRequest,
    service: ForecastServiceDep,
    session: DbSession,
    _: Annotated[User, Depends(require_permissions(Permission.REVIEW_FORECASTS))],
) -> object:
    forecast = await service.store_forecast_output(**payload.model_dump())
    await session.commit()
    return forecast


@router.post(
    "/generate",
    response_model=ForecastListResponse,
    status_code=201,
    summary="Generate demand forecasts",
    description="Generates LSTM-backed demand forecasts and stores the outputs for review.",
)
async def generate_forecasts(
    payload: ForecastGenerateRequest,
    service: ForecastServiceDep,
    session: DbSession,
    _: Annotated[User, Depends(require_permissions(Permission.REVIEW_FORECASTS))],
) -> ForecastListResponse:
    forecasts = await service.generate_forecasts(**payload.model_dump())
    await session.commit()
    return ForecastListResponse(
        items=list(forecasts),
        meta=PageMeta(offset=0, limit=max(len(forecasts), 1), count=len(forecasts)),
    )


@router.get("/{forecast_id}", response_model=ForecastResponse, summary="Get forecast")
async def get_forecast(
    forecast_id: UUID,
    service: ForecastServiceDep,
    _: Annotated[User, Depends(require_permissions(Permission.VIEW_FORECASTS))],
) -> object:
    return await service.get_forecast(forecast_id)
